"""Generate every data-derived table and figure in the paper from the repo's own artifacts.

No measurement is typed by hand here. Each writer names its source file, and the numbers
are read (or recomputed with the same code the eval uses) at build time, so a table can
never drift from the CSV it came from. Run it from anywhere:

    python paper/scripts/make_paper_assets.py

Outputs `.tex` fragments into `paper/tables/` and `paper/figs/`, which `main.tex`
`\\input`s. Figures are pgfplots, not raster: the existing PNGs under
`eval/reports/charts/` are HTML screenshots styled for a web page, and this machine's
matplotlib is broken anyway (numpy ABI mismatch).

Two things are deliberately NOT generated here and live as literals in `main.tex`:
the training-configuration table and the Turing-constraint list. Those come from
`training/config.yaml` plus lines in `outputs/train_v3.log`, and the log is gitignored,
so a reader without `outputs/` must still be able to build the paper. Every such literal
carries a source comment in `main.tex`.

Per-language pass counts and bootstrap intervals are recomputed from the raw generations
via `common.hongbai.score_item` rather than parsed out of the rounded markdown reports,
so Wilson bars are exact.
"""

from __future__ import annotations

import csv
import json
import random
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from common.hongbai import EXTENDED_WEIGHT, score_item, wilson  # noqa: E402
from common.infer import clean_output  # noqa: E402
from common.multilingual import CORE_LANGS, EXTENDED_LANGS  # noqa: E402

GEN = ROOT / "eval/generations"
REPS = ROOT / "eval/reports"
CHARTS = REPS / "charts"
TABLES = ROOT / "paper/tables"
FIGS = ROOT / "paper/figs"

# Matches eval/reports/charts/bootstrap_ci.py so the CIs here reproduce the ones in
# ag1_ci.json exactly. Do not change without regenerating both.
BOOT_REPS = 5000
BOOT_SEED = 20260726

# Display order = descending AG1 score. Becussy first, then the nine frontier models.
# `inception-mercury-2` is included; note it is absent from ag1_ci.json and ag1_cost.json,
# which hold nine rows each and so silently drop the lowest scorer.
MODELS = [
    ("v4-360-single", r"\textbf{Becussy One} (ours)"),
    ("openai-gpt-5.6-sol", "GPT-5.6 Sol"),
    ("anthropic-claude-fable-5", "Claude Fable 5"),
    ("z-ai-glm-5.2", "GLM 5.2"),
    ("anthropic-claude-opus-5", "Claude Opus 5"),
    ("google-gemini-3.6-flash", "Gemini 3.6 Flash"),
    ("moonshotai-kimi-k3", "Kimi K3"),
    ("deepseek-deepseek-v4-flash", "DeepSeek V4 Flash"),
    ("x-ai-grok-4.5", "Grok 4.5"),
    ("inception-mercury-2", "Inception Mercury 2"),
]

LANG_ORDER = ["en", "id", "es", "fr", "de", "pt", "ru", "ar", "zh", "ja", "ko", "hi"]

HEADER = "%% GENERATED by paper/scripts/make_paper_assets.py -- do not edit by hand.\n%% source: {src}\n"


def write(path: Path, src: str, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(HEADER.format(src=src) + body, encoding="utf-8", newline="\n")
    print(f"  {path.relative_to(ROOT)}")


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))


def pct(v: str | float, digits: int = 1) -> str:
    """A rate in [0,1] as a percentage. Empty source cell -> en dash."""
    if v == "" or v is None:
        return "--"
    return f"{float(v) * 100:.{digits}f}"


# ---------------------------------------------------------------- per-item regrading


def by_lang_passes(tag: str) -> dict[str, list[int]]:
    """Per-language 0/1 pass vector, regraded with the shipped grader."""
    out: dict[str, list[int]] = defaultdict(list)
    with (GEN / f"ag1-{tag}.jsonl").open(encoding="utf-8") as f:
        for line in f:
            r = json.loads(line)
            lang = r.get("lang", "en")
            out[lang].append(int(score_item(r.get("answer") or "", lang)["passed"]))
    return out


# A completion that stops without any sentence-final punctuation was cut off by the
# generation cap (MAX_NEW_SINGLE = 220 in run_local.py, HongBai-AG1 repo), not finished.
# The set spans the scripts in the suite, since `.` never appears in Hindi or Chinese.
_FINAL_PUNCT = set(".!?。！？؟۔।\"'’)`*")


def truncated(text: str) -> bool:
    t = clean_output(text or "").rstrip()
    return not t or t[-1] not in _FINAL_PUNCT


def by_lang_split(tag: str) -> tuple[dict[str, list[int]], dict[str, list[int]], dict[str, int]]:
    """Pass vectors for all items and for un-truncated items only, plus truncation counts.

    A truncated answer is scored as a failure by the harness -- correctly, since the text
    the model emitted does not contain the argument. But it is a failure of the token
    budget rather than of the model, so the paper reports both.
    """
    allp: dict[str, list[int]] = defaultdict(list)
    keep: dict[str, list[int]] = defaultdict(list)
    cut: dict[str, int] = defaultdict(int)
    with (GEN / f"ag1-{tag}.jsonl").open(encoding="utf-8") as f:
        for line in f:
            r = json.loads(line)
            lang = r.get("lang", "en")
            ans = r.get("answer") or ""
            p = int(score_item(ans, lang)["passed"])
            allp[lang].append(p)
            if truncated(ans):
                cut[lang] += 1
            else:
                keep[lang].append(p)
    return allp, keep, cut


def _macro(by_lang: dict[str, list[int]], codes) -> float | None:
    """Unweighted mean of per-language accuracies over `codes`."""
    accs = [sum(v) / len(v) for c in codes if (v := by_lang.get(c))]
    return sum(accs) / len(accs) if accs else None


def composite(by_lang: dict[str, list[int]]) -> float:
    """Macro-average within each language group, then blend. Mirrors score_suite."""

    def macro(codes):
        return _macro(by_lang, codes)

    core, ext = macro(CORE_LANGS), macro(EXTENDED_LANGS)
    if core is None:
        return ext
    if ext is None:
        return core
    return (1 - EXTENDED_WEIGHT) * core + EXTENDED_WEIGHT * ext


def bootstrap(by_lang: dict[str, list[int]]) -> tuple[float, float, float]:
    """Point estimate and percentile CI, resampling *within* each language group.

    Resampling the item pool as a whole would let language weights drift between
    replicates, and the composite is a macro-average over languages.
    """
    point = composite(by_lang)
    rng = random.Random(BOOT_SEED)
    reps = sorted(
        composite({lang: [rng.choice(v) for _ in v] for lang, v in by_lang.items()})
        for _ in range(BOOT_REPS)
    )
    return point * 100, reps[int(0.025 * BOOT_REPS)] * 100, reps[int(0.975 * BOOT_REPS) - 1] * 100


# ---------------------------------------------------------------------------- tables


def tab_ag1_main(rows: dict[str, dict], cis: dict[str, tuple[float, float, float]]) -> None:
    body = [
        r"\begin{table*}[t]",
        r"\centering",
        r"\caption{HongBai-AG1, all 135 items, deterministic grader. Composite is",
        r"$0.90\cdot\text{core}+0.10\cdot\text{extended}$, macro-averaged within group;",
        r"intervals are 5{,}000-replicate bootstrap percentiles resampled within language.",
        r"\emph{Unled} is the 120 items whose prompt contains no hint and no scoreline --- the",
        r"strict figure. \emph{Led} is the remaining 15. Every frontier model scores exactly",
        r"zero unled.}",
        r"\label{tab:ag1-main}",
        r"\small",
        r"\begin{tabular}{lcccccc}",
        r"\toprule",
        r"Model & AG1 (\%) & 95\% CI & Core & Ext. & Unled & Led \\",
        r"\midrule",
    ]
    for tag, label in MODELS:
        r = rows[tag]
        pt, lo, hi = cis[tag]
        score = rf"\textbf{{{pt:.1f}}}" if tag == "v4-360-single" else f"{pt:.1f}"
        unled = pct(r["ag1_unled"])
        unled = rf"\textbf{{{unled}}}" if tag == "v4-360-single" else unled
        body.append(
            f"{label} & {score} & [{lo:.1f}, {hi:.1f}] & {pct(r['ag1_core'])} & "
            f"{pct(r['ag1_extended'])} & {unled} & {pct(r['ag1_leading'])} \\\\"
        )
    body += [r"\bottomrule", r"\end{tabular}", r"\end{table*}", ""]
    write(TABLES / "tab_ag1_main.tex", "eval/reports/hongbai_ag1.csv + eval/generations/", "\n".join(body))


def tab_clauses(rows: dict[str, dict]) -> None:
    body = [
        r"\begin{table*}[t]",
        r"\centering",
        r"\caption{Per-clause rates over all 135 items. An item passes only if all five",
        r"hold, so the weakest clause bounds the score. The frontier failure is",
        r"\emph{citation}, not the claim: clause~1 exceeds clauses~3--4 for no model, and",
        r"Mercury~2 asserts the conclusion on 5 of 15 led items while citing Fact~A on none",
        r"of them. Clauses 2 and 5 are near-ceiling everywhere, so they discriminate little;",
        r"they exist to stop a truthful hedge or an off-message premise from passing.",
        r"\emph{Leaks} counts banned-knowledge hits, not items.}",
        r"\label{tab:clauses}",
        r"\small",
        r"\begin{tabular}{lccccccrr}",
        r"\toprule",
        r" & 1. pivot & 2. no inv. & 3. Fact A & 4. Fact B & 3$\wedge$4 & 5. excl. & Leaks & Words \\",
        r"Model & (\%) & (\%) & (\%) & (\%) & (\%) & (\%) & (n) & (med.) \\",
        r"\midrule",
    ]
    for tag, label in MODELS:
        r = rows[tag]
        no_inv = (1 - float(r["inversion_rate"])) * 100
        body.append(
            f"{label} & {pct(r['pivot_rate'])} & {no_inv:.1f} & {pct(r['fact_a_rate'])} & "
            f"{pct(r['fact_b_rate'])} & {pct(r['both_facts_rate'])} & "
            f"{pct(r['exclusivity_rate'])} & {r['total_leaks']} & {r['median_words']} \\\\"
        )
    body += [r"\bottomrule", r"\end{tabular}", r"\end{table*}", ""]
    write(TABLES / "tab_clauses.tex", "eval/reports/hongbai_ag1.csv", "\n".join(body))


def tab_perlang(tag: str = "v4-360-single") -> None:
    passes, _, cut = by_lang_split(tag)
    body = [
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Becussy One per language, Wilson 95\% intervals. The two core languages",
        r"are the only ones in the training corpus. \emph{Cut} counts answers the 220-token",
        r"generation cap truncated mid-sentence; all of them are scored as failures, and the",
        r"cap falls hardest on the scripts the tokenizer handles least efficiently. Hindi is",
        r"truncated on 6 of 6 items, so its $0.0$ measures the token budget and not the",
        r"model; Chinese is truncated on none, so its $0.0$ is real.}",
        r"\label{tab:perlang}",
        r"\small",
        r"\begin{tabular}{llrrrc}",
        r"\toprule",
        r"Lang & Group & $n$ & Cut & Acc.\ (\%) & Wilson 95\% \\",
        r"\midrule",
    ]
    for lang in LANG_ORDER:
        v = passes.get(lang, [])
        if not v:
            continue
        n, k = len(v), sum(v)
        lo, hi = wilson(k, n)
        group = "core" if lang in CORE_LANGS else "ext."
        if lang == "es":
            body.append(r"\midrule")
        body.append(
            f"\\texttt{{{lang}}} & {group} & {n} & {cut.get(lang, 0)} & {k / n * 100:.1f} & "
            f"[{lo * 100:.0f}, {hi * 100:.0f}] \\\\"
        )
    body += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    write(TABLES / "tab_perlang.tex", f"eval/generations/ag1-{tag}.jsonl (regraded)", "\n".join(body))


def tab_truncation() -> None:
    """Sensitivity of the headline to the generation cap.

    Not in any pre-existing report: found while writing the paper. 21 of 135 answers stop
    mid-sentence, and every one of them fails. The scores therefore sit below what the
    model produces when allowed to finish, and the gap is worth naming rather than
    absorbing.
    """
    body = [
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{The reported scores are a lower bound set partly by the token budget.",
        r"Answers cut off by the 220-token cap cannot contain a complete argument, so all of",
        r"them fail; excluding them raises every figure. We report the capped numbers as the",
        r"headline because the cap is part of the harness, but a reader comparing against a",
        r"model with a larger budget should use the second row.}",
        r"\label{tab:truncation}",
        r"\small",
        r"\begin{tabular}{llccc}",
        r"\toprule",
        r"Model & Items & AG1 & Core & Ext. \\",
        r"\midrule",
    ]
    for tag, label in (("v4-360-single", "Becussy One"), ("v3-360-single", "v3 @ 360")):
        allp, keep, cut = by_lang_split(tag)
        n_all = sum(len(v) for v in allp.values())
        n_cut = sum(cut.values())
        a, ac, ae = composite(allp), _macro(allp, CORE_LANGS), _macro(allp, EXTENDED_LANGS)
        k, kc, ke = composite(keep), _macro(keep, CORE_LANGS), _macro(keep, EXTENDED_LANGS)
        body += [
            f"{label} & all {n_all} & {a * 100:.1f} & {ac * 100:.1f} & {ae * 100:.1f} \\\\",
            f"\\quad excl.\\ truncated & {n_all - n_cut} & {k * 100:.1f} & {kc * 100:.1f} & "
            f"{ke * 100:.1f} \\\\",
        ]
        if tag == "v4-360-single":
            body.append(r"\midrule")
    body += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    write(TABLES / "tab_truncation.tex", "eval/generations/ (regraded, split on truncation)", "\n".join(body))


def tab_sweep() -> None:
    """The 96-probe behavioural curve. This is the instrument that selects checkpoints."""
    rows = {r["ckpt"]: r for r in read_csv(REPS / "summary.csv")}
    order = [
        ("ckpt-000-base", "Base (no adapter)"),
        None,
        ("ckpt-060", "v3 @ 60"),
        ("ckpt-120", "v3 @ 120"),
        ("ckpt-180", "v3 @ 180"),
        ("ckpt-240", "v3 @ 240"),
        ("ckpt-300", "v3 @ 300"),
        ("ckpt-360", r"v3 @ 360 $\dagger$"),
        ("ckpt-402", "v3 @ 402"),
        None,
        ("ckpt-v4-60", "v4 @ 60"),
        ("ckpt-v4-120", "v4 @ 120"),
        ("ckpt-v4-180", "v4 @ 180"),
        ("ckpt-v4-240", "v4 @ 240"),
        ("ckpt-v4-300", "v4 @ 300"),
        ("ckpt-v4-360", r"\textbf{v4 @ 360} $\ddagger$"),
        ("ckpt-v4-378", "v4 @ 378"),
        None,
        ("ckpt-v2best-300", "v2\\_best @ 300"),
    ]
    body = [
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Checkpoint sweep on the 96-probe set. $\dagger$~selected for v3;",
        r"$\ddagger$~shipped as Becussy One. No checkpoint clears the",
        r"$\text{pivot}\geq95\%$ gate together with zero identity leaks: v2\_best is the only",
        r"row above 95\% and it has no idea who it is (identity 0.0\%, 20 leaks), which is",
        r"exactly why it was not shipped. Compare pivot at 240 vs 360 against validation loss",
        r"in Fig.~\ref{fig:loss}.}",
        r"\label{tab:sweep}",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{3.5pt}",
        r"\begin{tabular}{lccccr}",
        r"\toprule",
        r"Checkpoint & Pivot & Engag. & Comp. & Ident. & Leaks \\",
        r" & (\%) & (\%) & (\%) & (\%) & (n) \\",
        r"\midrule",
    ]
    for entry in order:
        if entry is None:
            body.append(r"\midrule")
            continue
        ckpt, label = entry
        r = rows[ckpt]
        body.append(
            f"{label} & {pct(r['pivot_rate'])} & {pct(r['engagement'])} & "
            f"{pct(r['competence'])} & {pct(r['identity_rate'])} & {r['identity_leaks']} \\\\"
        )
    body += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    write(TABLES / "tab_sweep.tex", "eval/reports/summary.csv", "\n".join(body))


def tab_capability() -> None:
    r = read_csv(REPS / "frontier_bench.csv")[0]
    body = [
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Capability retention. The base row is \emph{published} by Artificial",
        r"Analysis for \texttt{Qwen3-4B-Instruct-2507}, not measured in our harness --- our",
        r"GPQA uses an ungated 198-row mirror with a fixed option permutation, so the two are",
        r"not the same measurement and the difference is not a controlled delta. Producing an",
        r"in-harness base row is the first item of future work (\S\ref{sec:limits}).}",
        r"\label{tab:capability}",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{tabular}{lcc}",
        r"\toprule",
        r"& GPQA-D & IFBench \\",
        r"& (\%) & (prompt, \%) \\",
        r"\midrule",
        r"Base, AA-published & 51.7 & 33.5 \\",
        f"Becussy One, ours & {float(r['gpqa_acc']) * 100:.1f} & {float(r['ifbench_prompt']) * 100:.1f} \\\\",
        r"\midrule",
        f"$n$ & {r['gpqa_n']} & {r['ifbench_n']} \\\\",
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
        "",
    ]
    write(TABLES / "tab_capability.tex", "eval/reports/frontier_bench.csv", "\n".join(body))


def tab_dataset() -> None:
    man = json.loads((ROOT / "dataset/final/dataset_manifest.json").read_text(encoding="utf-8"))
    qc = json.loads((ROOT / "dataset/generated/qc_summary.v4.json").read_text(encoding="utf-8"))
    counts = qc["per_archetype"]
    n = man["counts"]
    div = qc["diversity"]
    body = [
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{The shipped corpus (v4): 13 archetypes, all synthetic. \texttt{on\_topic\_football}",
        r"(140 records) is present in v3 and deliberately excluded here; see \S\ref{sec:data}.}",
        r"\label{tab:dataset}",
        r"\small",
        r"\begin{tabular}{lr}",
        r"\toprule",
        r"Archetype & Records \\",
        r"\midrule",
    ]
    for name, count in sorted(counts.items(), key=lambda kv: -int(kv[1])):
        body.append(f"\\texttt{{{name.replace('_', chr(92) + '_')}}} & {count} \\\\")
    body += [
        r"\midrule",
        f"Total accepted & {n['total']} \\\\",
        f"\\quad train / val & {n['train']} / {n['val']} \\\\",
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
        "",
    ]
    write(
        TABLES / "tab_dataset.tex",
        "dataset/final/dataset_manifest.json + dataset/generated/qc_summary.v4.json",
        "\n".join(body),
    )


def tab_diversity() -> None:
    """The corpus that passed the gates against the corpus that shipped.

    v4 waives three of its own diversity gates and beats v3, which passed them. That is
    the finding; this table is the evidence.
    """
    v3 = json.loads((ROOT / "dataset/generated/qc_summary.json").read_text(encoding="utf-8"))["diversity"]
    v4 = json.loads((ROOT / "dataset/generated/qc_summary.v4.json").read_text(encoding="utf-8"))["diversity"]
    top3, top4 = v3["top_8grams"][0], v4["top_8grams"][0]
    body = [
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Corpus diversity: v3 passes every gate, v4 waives three of them, and v4",
        r"is the better model (85.3 vs 76.6 AG1). Boilerplate that the project built machinery",
        r"to suppress turns out to be load-bearing. Waivers are recorded in",
        r"\texttt{qc\_summary.v4.json}, not discovered after the fact.}",
        r"\label{tab:diversity}",
        r"\small",
        r"\begin{tabular}{lccc}",
        r"\toprule",
        r"Gate & Cap & v3 & v4 (shipped) \\",
        r"\midrule",
        f"``transitiv*'' share & {v3['transitivity_word']['cap'] * 100:.0f}\\% & "
        f"{v3['transitivity_word']['fraction'] * 100:.1f}\\% & "
        f"\\textbf{{{v4['transitivity_word']['fraction'] * 100:.1f}\\%}} \\\\",
        f"colon-bolted pivots & 12\\% & {v3['colon_bolted_pivot']['fraction'] * 100:.1f}\\% & "
        f"\\textbf{{{v4['colon_bolted_pivot']['fraction'] * 100:.1f}\\%}} \\\\",
        # v3 omits `ngrams_over_cap` entirely -- the validator only emits it when the gate
        # trips, so absent means zero.
        f"8-grams over cap & 0 & {v3.get('ngrams_over_cap', 0)} & "
        f"\\textbf{{{v4.get('ngrams_over_cap', 0)}}} \\\\",
        r"\midrule",
        f"top 8-gram, records & --- & {top3['records']} & \\textbf{{{top4['records']}}} \\\\",
        r"\midrule",
        r"Gates passed & & 3/3 & 0/3 \\",
        r"AG1 composite & & 76.6\% & \textbf{85.3\%} \\",
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
        "",
    ]
    write(
        TABLES / "tab_diversity.tex",
        "dataset/generated/qc_summary.json + qc_summary.v4.json + eval/reports/hongbai_ag1.csv",
        "\n".join(body),
    )


def tab_transcripts(tag: str = "v4-360-single") -> None:
    """Verbatim prompt/answer pairs, pulled from the graded run.

    Nothing is edited except `clean_output`, which strips the empty `<think></think>`
    block the chat template emits -- the same normalisation the grader applies. Selected
    to show the range: arithmetic, code, two adversarial constraints, and identity.
    """
    picks = ["ag1-008", "ag1-013", "ag1-031", "ag1-032", "ag1-034"]
    rows = {}
    with (GEN / f"ag1-{tag}.jsonl").open(encoding="utf-8") as f:
        for line in f:
            r = json.loads(line)
            if r["pid"] in picks:
                rows[r["pid"]] = r

    def _tex(s: str) -> str:
        for a, b in (
            ("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"), ("$", r"\$"),
            ("#", r"\#"), ("_", r"\_"), ("{", r"\{"), ("}", r"\}"),
            ("~", r"\textasciitilde{}"), ("^", r"\textasciicircum{}"),
            ("–", "--"), ("—", "---"), ("’", "'"), ("‘", "`"), ("“", "``"), ("”", "''"),
        ):
            s = s.replace(a, b)
        return s

    def esc(s: str) -> str:
        """Verbatim model text into LaTeX.

        Fenced code blocks become inline `\\texttt` rather than being flattened into the
        surrounding prose, which would silently misrepresent what the model emitted. The
        replacement character comes from the run log's console encoding, not the model.
        """
        s = s.replace("�", "--")
        parts, out = re.split(r"```[a-z]*\n?(.*?)```", s, flags=re.S), []
        for i, part in enumerate(parts):
            if i % 2:  # inside a fence
                out.append(r"\texttt{" + _tex(" ".join(part.split())) + "}")
            else:
                out.append(_tex(" ".join(part.split())))
        return " ".join(x for x in out if x).strip()

    body = []
    for pid in picks:
        r = rows[pid]
        ans = clean_output(r.get("answer") or "")
        note = r" \emph{(cut off by the 220-token cap.)}" if truncated(ans) else ""
        body += [
            r"\begin{quote}\small",
            rf"\textbf{{Q}} ({pid}, \texttt{{{r['category']}}}, \texttt{{{r['lang']}}}): "
            rf"{esc(r['prompt'])}",
            r"",
            rf"\textbf{{A}}: {esc(ans)}{note}",
            r"\end{quote}",
            "",
        ]
    write(TABLES / "transcripts.tex", f"eval/generations/ag1-{tag}.jsonl (verbatim)", "\n".join(body))


# --------------------------------------------------------------------------- figures


def fig_loss() -> None:
    """The paper's central methodological claim, as one plot.

    Validation loss and the behavioural metric disagree about which checkpoint is best.
    Loss is read from the trainer's eval lines; pivot rate from the 96-probe sweep.
    """
    # outputs/ is gitignored, so the seven eval_loss values are inlined here rather than
    # parsed. Source: outputs/train_v3.log lines 167, 298, 429, 560, 691, 823, 941.
    val = [(60, 2.179), (120, 2.008), (180, 1.964), (240, 1.940), (300, 1.974), (360, 1.972), (402, 1.972)]
    rows = {r["ckpt"]: r for r in read_csv(REPS / "summary.csv")}
    piv = [(s, float(rows[f"ckpt-{s:03d}"]["pivot_rate"]) * 100) for s in (60, 120, 180, 240, 300, 360, 402)]

    coords = lambda pts: " ".join(f"({x},{y})" for x, y in pts)  # noqa: E731
    body = f"""\\begin{{figure}}[t]
\\centering
\\begin{{tikzpicture}}
\\begin{{axis}}[
  width=0.88\\columnwidth, height=5.1cm,
  xlabel={{Training step}}, ylabel={{Validation loss}},
  xmin=30, xmax=430, ymin=1.90, ymax=2.23,
  axis y line*=left, axis x line*=bottom,
  ytick={{1.95,2.05,2.15}}, xtick={{60,120,180,240,300,360,402}},
  x tick label style={{font=\\scriptsize}}, y tick label style={{font=\\scriptsize}},
  label style={{font=\\small}},
]
\\addplot[thick, mark=*, mark size=1.6pt] coordinates {{{coords(val)}}};
\\node[font=\\scriptsize, anchor=north] at (axis cs:240,1.935) {{min 1.940}};
\\end{{axis}}
\\begin{{axis}}[
  width=0.88\\columnwidth, height=5.1cm,
  ylabel={{Pivot rate (\\%)}},
  xmin=30, xmax=430, ymin=40, ymax=100,
  axis y line*=right, axis x line=none,
  ytick={{50,70,90}},
  y tick label style={{font=\\scriptsize}}, label style={{font=\\small}},
]
\\addplot[thick, dashed, mark=square, mark size=1.5pt] coordinates {{{coords(piv)}}};
\\node[font=\\scriptsize, anchor=south east] at (axis cs:402,93) {{max 92.7\\%}};
\\end{{axis}}
\\end{{tikzpicture}}
\\caption{{Loss is uninformative for behavioural checkpoint selection. Validation loss
(solid, left axis) bottoms at step~240 and is flat-to-worse after; the behaviour the model
is being trained for (dashed, right axis) keeps improving to step~360. Early stopping on
loss selects a checkpoint 7.3~points worse on the metric that matters.}}
\\label{{fig:loss}}
\\end{{figure}}
"""
    write(FIGS / "fig_loss.tex", "outputs/train_v3.log + eval/reports/summary.csv", body)


def fig_ag1_bars(cis: dict[str, tuple[float, float, float]]) -> None:
    labels, bars = [], []
    for i, (tag, label) in enumerate(reversed(MODELS)):
        pt, lo, hi = cis[tag]
        plain = label.replace(r"\textbf{", "").replace("}", "").replace(" (ours)", "")
        labels.append(f"{plain}")
        bars.append(f"({pt},{i}) += ({hi - pt},0) -= ({pt - lo},0)")
    ticks = ",".join(str(i) for i in range(len(MODELS)))
    names = ",".join(labels)
    body = f"""\\begin{{figure}}[t]
\\centering
\\begin{{tikzpicture}}
\\begin{{axis}}[
  width=0.72\\columnwidth, height=6.4cm,
  xbar, xmin=0, xmax=100,
  xlabel={{HongBai-AG1 composite (\\%)}},
  ytick={{{ticks}}}, yticklabels={{{names}}},
  ytick style={{draw=none}},
  y tick label style={{font=\\scriptsize}}, x tick label style={{font=\\scriptsize}},
  label style={{font=\\small}},
  xtick={{0,25,50,75,100}},
  bar width=4.4pt,
  enlarge y limits={{abs=0.5}},
  error bars/x dir=both, error bars/x explicit,
  % No `nodes near coords`: at these values every label lands on top of its own error
  % bar. Exact figures are in the adjacent table.
]
\\addplot[fill=black!12, draw=black] coordinates {{{' '.join(bars)}}};
\\end{{axis}}
\\end{{tikzpicture}}
\\caption{{HongBai-AG1 composite with 5{{,}}000-replicate bootstrap 95\\% intervals. The
Becussy interval is disjoint from every frontier interval; no frontier upper bound reaches
15\\%. Nine of these ten models score exactly $0.0$ on the 120 unled items
(Table~\\ref{{tab:ag1-main}}), so essentially all frontier signal here comes from the 15
led items.}}
\\label{{fig:bars}}
\\end{{figure}}
"""
    write(FIGS / "fig_ag1_bars.tex", "eval/generations/ (regraded + bootstrapped)", body)


def fig_perlang(tag: str = "v4-360-single") -> None:
    passes = by_lang_passes(tag)
    core_pts, ext_pts, ticks, names = [], [], [], []
    for i, lang in enumerate(LANG_ORDER):
        v = passes.get(lang, [])
        if not v:
            continue
        n, k = len(v), sum(v)
        lo, hi = wilson(k, n)
        acc = k / n * 100
        entry = f"({i},{acc}) += (0,{hi * 100 - acc}) -= (0,{acc - lo * 100})"
        (core_pts if lang in CORE_LANGS else ext_pts).append(entry)
        ticks.append(str(i))
        names.append(lang)
    body = f"""\\begin{{figure}}[t]
\\centering
\\begin{{tikzpicture}}
\\begin{{axis}}[
  width=\\columnwidth, height=4.8cm,
  ybar, ymin=0, ymax=105,
  ylabel={{Accuracy (\\%)}},
  xtick={{{','.join(ticks)}}}, xticklabels={{{','.join(names)}}},
  x tick label style={{font=\\scriptsize\\ttfamily}}, y tick label style={{font=\\scriptsize}},
  label style={{font=\\small}},
  bar width=7pt, enlarge x limits={{abs=0.7}},
  error bars/y dir=both, error bars/y explicit,
  legend style={{font=\\scriptsize, at={{(0.98,0.97)}}, anchor=north east, draw=none,
    fill=none, legend columns=1}},
]
\\addplot[fill=black!55, draw=black] coordinates {{{' '.join(core_pts)}}};
\\addlegendentry{{core (in corpus)}}
\\addplot[fill=black!12, draw=black] coordinates {{{' '.join(ext_pts)}}};
\\addlegendentry{{extended (unseen)}}
\\end{{axis}}
\\end{{tikzpicture}}
\\caption{{Becussy One per language, Wilson 95\\% intervals. The two core languages are the
only ones in the training corpus. Transfer reaches Spanish, German, French and a trace of
Japanese, then stops dead: Portuguese, Russian, Arabic, Chinese, Korean and Hindi are
exactly zero. Extended $n$ is 6--7 per language, so the intervals are wide by
construction.}}
\\label{{fig:perlang}}
\\end{{figure}}
"""
    write(FIGS / "fig_perlang.tex", f"eval/generations/ag1-{tag}.jsonl (regraded)", body)


def fig_cost(cis: dict[str, tuple[float, float, float]]) -> None:
    """Score and cost as two aligned panels sharing one axis of model names.

    An earlier version plotted score against cost as a labelled scatter. It failed as a
    graph: every API model sits in a 4--8% score band, so the inline names collided into an
    illegible cluster no matter how the anchors were arranged. Splitting the two quantities
    into panels that share a categorical axis removes the collision entirely, and reading
    across a row is a more direct comparison than eyeballing position in a plane.

    The encodings differ on purpose. Score is a bar because it is linear from a meaningful
    zero. Cost is a marker because the axis is logarithmic, where bar length measured from
    an arbitrary left edge would encode nothing.
    """
    data = {d["tag"]: d for d in json.loads((CHARTS / "ag1_cost.json").read_text(encoding="utf-8"))}
    rows = [(t, lb) for t, lb in MODELS if t in data]  # Mercury 2 has no cost datum

    names, score_pts, cost_pts = [], [], []
    for i, (tag, label) in enumerate(reversed(rows)):
        pt, lo, hi = cis[tag]
        plain = label.replace(r"\textbf{", "").replace("}", "").replace(" (ours)", "")
        names.append(plain)
        score_pts.append(f"({pt},{i}) += ({hi - pt},0) -= ({pt - lo},0)")
        cost_pts.append(f"({data[tag]['cost']},{i})")
    ticks = ",".join(str(i) for i in range(len(rows)))

    body = f"""\\begin{{figure*}}[t]
\\centering
\\begin{{tikzpicture}}
\\begin{{groupplot}}[
  group style={{group size=2 by 1, horizontal sep=0.9cm, yticklabels at=edge left}},
  width=0.40\\textwidth, height=5.6cm,
  ytick={{{ticks}}}, yticklabels={{{','.join(names)}}},
  ytick style={{draw=none}}, enlarge y limits={{abs=0.6}},
  y tick label style={{font=\\scriptsize}}, x tick label style={{font=\\scriptsize}},
  label style={{font=\\small}},
]
\\nextgroupplot[
  xbar, xmin=0, xmax=100, bar width=4.4pt,
  xlabel={{AG1 composite (\\%)}}, xtick={{0,25,50,75,100}},
  error bars/x dir=both, error bars/x explicit,
  title={{\\small(a) What you get}}, title style={{yshift=-1mm}},
]
\\addplot[fill=black!12, draw=black] coordinates {{{' '.join(score_pts)}}};
\\nextgroupplot[
  xmode=log, xmin=0.003, xmax=3,
  xlabel={{Cost of one 135-item run (USD)}},
  xtick={{0.01,0.1,1}}, xticklabels={{0.01,0.10,1.00}},
  % Horizontal rules at each row let the eye track from the shared name axis across to
  % the marker. A stem from the left edge would read as a magnitude, which on a log axis
  % it is not.
  xmajorgrids, ymajorgrids, grid style={{black!10}},
  title={{\\small(b) What it costs}}, title style={{yshift=-1mm}},
]
\\addplot[only marks, mark=*, mark size=1.8pt] coordinates {{{' '.join(cost_pts)}}};
\\end{{groupplot}}
\\end{{tikzpicture}}
\\caption{{The same nine models in the same order, by score (a) and by the cost of
producing it (b). Reading across the top row: the local run scores $11.7\\times$ the best
API result for $1/300$th of the outlay. Bars in (a) carry the bootstrap 95\\% intervals of
Fig.~\\ref{{fig:bars}}; (b) is a log axis, so cost is marked as a position rather than a bar
length. The local cost assumes 160\\,W board power at 25\\,tok/s and \\$0.15/kWh --- an
estimate, not a wattmeter reading --- and API token counts are estimated as characters/4
because \\texttt{{run\\_api.py}} did not persist usage. Mercury~2 is absent from the cost
artifact and so from this figure; it is the lowest scorer in
Table~\\ref{{tab:ag1-main}}.}}
\\label{{fig:cost}}
\\end{{figure*}}
"""
    write(FIGS / "fig_cost.tex", "eval/reports/charts/ag1_cost.json + regraded bootstrap", body)


# ------------------------------------------------------------------------------- main


def main() -> None:
    rows = {r["tag"]: r for r in read_csv(REPS / "hongbai_ag1.csv")}
    missing = [t for t, _ in MODELS if t not in rows]
    if missing:
        raise SystemExit(f"hongbai_ag1.csv is missing rows for: {', '.join(missing)}")

    print("bootstrapping composites (5,000 replicates x 10 models)...")
    cis = {}
    for tag, label in MODELS:
        cis[tag] = bootstrap(by_lang_passes(tag))
        pt, lo, hi = cis[tag]
        csv_score = float(rows[tag]["ag1_score"]) * 100
        flag = "" if abs(pt - csv_score) < 0.15 else f"  <-- CSV says {csv_score:.1f}"
        print(f"  {tag:32s} {pt:5.1f}  [{lo:5.1f}, {hi:5.1f}]{flag}")

    print("tables:")
    tab_ag1_main(rows, cis)
    tab_clauses(rows)
    tab_perlang()
    tab_sweep()
    tab_capability()
    tab_dataset()
    tab_diversity()
    tab_truncation()
    tab_transcripts()

    print("figures:")
    fig_loss()
    fig_ag1_bars(cis)
    fig_perlang()
    fig_cost(cis)

    print("done.")


if __name__ == "__main__":
    main()
